# Generated by Django 2.2.7 on 2020-01-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('item_type', models.CharField(max_length=10)),
                ('swapi_url', models.CharField(max_length=50)),
                ('favorite_count', models.IntegerField()),
            ],
        ),
    ]
