# Generated by Django 2.2.7 on 2020-01-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapi_info', '0002_auto_20200114_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='item_type',
            field=models.CharField(max_length=9),
        ),
    ]
