# Generated by Django 2.2.7 on 2020-01-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapi_info', '0003_auto_20200115_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='item_type',
            field=models.CharField(choices=[('films', 'Films'), ('people', 'People'), ('planets', 'Planets'), ('species', 'Species'), ('starships', 'Starships'), ('vehicles', 'Vehicles')], max_length=1),
        ),
    ]
